const businesses = [
    {
      id: '1',
      name: 'Tasty Treats Bakery',
      address: '123 Main St',
      city: 'Cityville',
      state: 'CA',
      zipCode: '12345',
      phoneNumber: '123-456-7890',
      category: 'Bakery',
      subcategories: ['Cakes', 'Pastries'],
      website: 'https://tastytreats.com',
      email: 'info@tastytreats.com',
      reviews: [],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '2',
      name: 'Gear Up Bike Shop',
      address: '456 Elm St',
      city: 'Townsville',
      state: 'NY',
      zipCode: '67890',
      phoneNumber: '987-654-3210',
      category: 'Bike Shop',
      subcategories: ['Mountain Bikes', 'Road Bikes'],
      website: 'https://gearupbikes.com',
      email: 'sales@gearupbikes.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '3',
      name: 'Blooming Flowers',
      address: '789 Oak St',
      city: 'Villageton',
      state: 'FL',
      zipCode: '54321',
      phoneNumber: '555-123-4567',
      category: 'Florist',
      subcategories: ['Bouquets', 'Arrangements'],
      website: 'https://bloomingflowers.com',
      email: 'orders@bloomingflowers.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '4',
      name: 'Tech Gadgets',
      address: '321 Maple Ave',
      city: 'Techville',
      state: 'TX',
      zipCode: '98765',
      phoneNumber: '111-222-3333',
      category: 'Electronics',
      subcategories: ['Smartphones', 'Laptops'],
      website: 'https://techgadgets.com',
      email: 'support@techgadgets.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '5',
      name: 'Fashion Forward Boutique',
      address: '654 Pine St',
      city: 'Fashiontown',
      state: 'IL',
      zipCode: '24680',
      phoneNumber: '444-555-6666',
      category: 'Clothing',
      subcategories: ['Women\'s Apparel', 'Accessories'],
      website: 'https://fashionforwardboutique.com',
      email: 'info@fashionforwardboutique.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '6',
      name: 'Cosmic Coffee',
      address: '987 Cedar Rd',
      city: 'Coffeeburg',
      state: 'WA',
      zipCode: '13579',
      phoneNumber: '777-888-9999',
      category: 'Coffee Shop',
      subcategories: ['Espresso', 'Pastries'],
      website: 'https://cosmiccoffee.com',
      email: 'orders@cosmiccoffee.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '7',
      name: 'Bookworm Haven',
      address: '741 Birch Ln',
      city: 'Booksville',
      state: 'MA',
      zipCode: '97531',
      phoneNumber: '222-333-4444',
      category: 'Bookstore',
      subcategories: ['Fiction', 'Non-Fiction'],
      website: 'https://bookwormhaven.com',
      email: 'info@bookwormhaven.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '8',
      name: 'Fitness Forever Gym',
      address: '852 Walnut St',
      city: 'Fitnessville',
      state: 'CO',
      zipCode: '86420',
      phoneNumber: '555-666-7777',
      category: 'Gym',
      subcategories: ['Weights', 'Cardio'],
      website: 'https://fitnessforevergym.com',
      email: 'membership@fitnessforevergym.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: [],
    },
    {
      id: '9',
      name: 'Pawsome Pet Supplies',
      address: '963 Spruce Ave',
      city: 'Petsburg',
      state: 'AZ',
      zipCode: '75319',
      phoneNumber: '888-999-0000',
      category: 'Pet Store',
      subcategories: ['Dog Food', 'Cat Toys'],
      website: 'https://pawsomepetsupplies.com',
      email: 'orders@pawsomepetsupplies.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: ["https://static.vecteezy.com/system/resources/thumbnails/024/193/043/small/modern-office-building-business-center-neural-network-ai-generated-photo.jpg"],
    },
    {
      id: '10',
      name: 'Green Thumb Nursery',
      address: '159 Sycamore Dr',
      city: 'Gardentown',
      state: 'OR',
      zipCode: '24680',
      phoneNumber: '111-222-3333',
      category: 'Garden Center',
      subcategories: ['Plants', 'Gardening Tools'],
      website: 'https://greenthumbnursery.com',
      email: 'info@greenthumbnursery.com',
      reviews: ['5 stars', '3 stars', '1 star'],
      photos: [],
    }
  ];

  module.exports = businesses;